name: Denis
channels:
  - defaults
dependencies:
  - keras
  - matplotlib
  - numpy
  - pandas
  - patsy
  - pprint
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - sqlite
  - statsmodels
  - tensorflow

